name: 🚀 Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or change to your default branch

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
    - name: 📥 Checkout source
      uses: actions/checkout@v4

    - name: 🧹 Remove private API keys
      run: |
        sed -i '/const OPENROUTER_API_KEY/d' index.html
        echo "<!-- API key removed for public deployment -->" >> index.html

    - name: 🚀 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
